#!/usr/bin/env bash
# Usage: gen_nyan_frames.sh <gif> <builddir> <outfile>
set -e
GIF="$1"
BUILDDIR="$2"
OUTFILE="$3"

# Split GIF into 16 coalesced frames
convert "$GIF" -coalesce +adjoin "$BUILDDIR/nyan_frame_%02d.png"

{
    echo "#pragma once"
    echo "// Auto-generated by cmake/gen_nyan_frames.sh -- do not edit"
    echo ""

    for i in $(seq -w 0 15); do
        xxd -i "$BUILDDIR/nyan_frame_${i}.png" \
            | sed "s/unsigned char .*\[\]/static const unsigned char kNyanFrame${i}[]/" \
            | sed "s/unsigned int .*_len/static const unsigned int kNyanFrame${i}Len/"
        echo ""
    done

    echo "static const unsigned char* const kNyanFrameData[16] = {"
    for i in $(seq -w 0 15); do
        echo "    kNyanFrame${i},"
    done
    echo "};"
    echo ""
    echo "static const unsigned int kNyanFrameSize[16] = {"
    for i in $(seq -w 0 15); do
        echo "    kNyanFrame${i}Len,"
    done
    echo "};"
} > "$OUTFILE"
