#!/usr/bin/env bash
# Usage: gen_nyan_frames.sh <assets_dir> <outfile>
# Packs pre-edited RGBA PNGs from assets_dir into a C header.
set -e

[ $# -eq 2 ] || { echo "Usage: $0 <assets_dir> <outfile>" >&2; exit 1; }

ASSETSDIR="$1"
OUTFILE="$2"

FRAMES=("$ASSETSDIR"/nyan_frame_[0-9][0-9].png)
FRAME_COUNT=${#FRAMES[@]}

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
{
    echo "#pragma once"
    echo "// Auto-generated by cmake/gen_nyan_frames.sh -- do not edit"
    echo "#define NYAN_FRAME_COUNT ${FRAME_COUNT}"
    echo ""

    i=0
    for f in "${FRAMES[@]}"; do
        TAG=$(printf "%02d" "$i")
        xxd -i "$f" \
            | sed "s/unsigned char .*\[\]/static const unsigned char kNyanFrame${TAG}[]/" \
            | sed "s/unsigned int .*_len/static const unsigned int kNyanFrame${TAG}Len/"
        echo ""
        i=$(( i + 1 ))
    done

    echo "static const unsigned char* const kNyanFrameData[${FRAME_COUNT}] = {"
    for j in $(seq 0 $(( FRAME_COUNT - 1 ))); do
        echo "    kNyanFrame$(printf "%02d" "$j"),"
    done
    echo "};"
    echo ""
    echo "static const unsigned int kNyanFrameSize[${FRAME_COUNT}] = {"
    for j in $(seq 0 $(( FRAME_COUNT - 1 ))); do
        echo "    kNyanFrame$(printf "%02d" "$j")Len,"
    done
    echo "};"
} > "$TMPFILE" && mv "$TMPFILE" "$OUTFILE"
