#!/usr/bin/env bash
# Usage: gen_nyan_frames.sh <gif> <builddir> <outfile>
set -e

[ $# -eq 3 ] || { echo "Usage: $0 <gif> <builddir> <outfile>" >&2; exit 1; }

GIF="$1"
BUILDDIR="$2"
OUTFILE="$3"

FRAME_COUNT=$(identify -format '%n\n' "$GIF" | head -1)

# Split all GIF frames (coalesced)
convert "$GIF" -coalesce +adjoin "$BUILDDIR/nyan_frame_%02d.png"

LAST=$(( FRAME_COUNT - 1 ))
LAST_PADDED=$(printf "%02d" "$LAST")

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
{
    echo "#pragma once"
    echo "// Auto-generated by cmake/gen_nyan_frames.sh -- do not edit"
    echo "#define NYAN_FRAME_COUNT ${FRAME_COUNT}"
    echo ""

    for i in $(seq -w 0 "$LAST_PADDED"); do
        xxd -i "$BUILDDIR/nyan_frame_${i}.png" \
            | sed "s/unsigned char .*\[\]/static const unsigned char kNyanFrame${i}[]/" \
            | sed "s/unsigned int .*_len/static const unsigned int kNyanFrame${i}Len/"
        echo ""
    done

    echo "static const unsigned char* const kNyanFrameData[${FRAME_COUNT}] = {"
    for i in $(seq -w 0 "$LAST_PADDED"); do
        echo "    kNyanFrame${i},"
    done
    echo "};"
    echo ""
    echo "static const unsigned int kNyanFrameSize[${FRAME_COUNT}] = {"
    for i in $(seq -w 0 "$LAST_PADDED"); do
        echo "    kNyanFrame${i}Len,"
    done
    echo "};"
} > "$TMPFILE" && mv "$TMPFILE" "$OUTFILE"
